config/routes.rb
Rails.application.routes.draw do

  get '/customers/withdraw', to: 'customers#withdraw'

  namespace :staffs do
     root to: 'home#top'
     #put 'orders/item/:id', to:'orders#item_update', as:'order_item'
     patch 'orders/item/:id', to:'orders#item_update', as:'order_item'
     get 'orders/customers/:id', to:'orders#index', as: 'orders_search'
     resources :orders, only:[ :index, :show, :edit, :update ]


     resources :customers, only:[ :index, :show, :edit, :update, :destroy ]
     resources :items, only:[ :index, :show, :new, :create, :edit, :update ]
     resources :genres, only:[ :index, :new, :create, :edit, :update ]
   end

  devise_for :staffs, controllers: {
        sessions: 'staffs/sessions',
        registrations: 'staffs/registrations'
      }

  root to: 'home#top'
  devise_for :customers, controllers: {
        sessions: 'customers/sessions',
        registrations: 'customers/registrations'
      }


  root to: 'home#top'
  get '/home/about', to: 'home#about'
  resources :customers, only:[ :edit, :show, :update, :destroy ]
  resources :customers, only:[ :edit, :show, :update,:destroy ]
  resources :items, only:[ :index, :show ] do
  resources :cart_items, only: [ :index, :update, :create, :destroy ]
  end
  get 'orders/check', to: 'orders#check'
  get 'orders/thanks', to: 'orders#thanks'

  delete '/cart_items/', to: 'cart_items#clear' #カートアイテム全件削除
  resources :orders, only:[ :index, :new, :create, :show ]
  post 'orders/check', to: 'orders#check'



  resources :sub_addresses, only:[ :index, :show , :new, :create, :edit, :update, :destroy ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end



 #  namespace :admins do
 #    get 'top', to: 'home#top'
	#   resources :orders, only:[ :index, :show, :edit, :update ]
	#   resources :customers, only:[ :index, :show, :edit, :update ]
	#   resources :items, only:[ :index, :show, :new, :create, :edit, :update ]
	#   resources :genres, only:[ :index, :new, :create, :edit, :update ]
	# end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @cart_items = current_customer.cart_items
  end

  def create
    @item = Item.find(params[:item_id])

    @cart_item  = current_customer.cart_items.find_by(item_id: params[:item_id])
    if @cart_item
      @cart_item.quantity += params[:cart_item][:quantity].to_i
    else
      @cart_item = CartItem.new(cart_item_params)
      @cart_item.item_id = params[:item_id]
      @cart_item.customer_id = current_customer.id
    end
      @cart_item.save
      redirect_to item_cart_items_path(@cart_item)
  end

  def edit
    @cart_item = CartItem.find(params[:id])
  end

  def update
    @cart_item = CartItem.find(params[:id])
      @cart_item.update(cart_item_params)
      redirect_to item_cart_items_path(@cart_item)
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to item_cart_items_path(current_customer.id)
  end

  def clear
    @cart_items = CartItem.all
    @cart_items.destroy_all
    redirect_to item_cart_items_path(current_customer.id)
  end

  private
  def cart_item_params
      params.require(:cart_item).permit(:quantity)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="row row-eq-height">
	<div class="col-xs-8">
		<h1>ショッピングカート</h1>
	</div>
	<div class="col-xs-4">
		 <%= link_to 'カートを空にする', cart_items_path, method: :delete, class: "btn btn-primary pull-right" %>
	</div>
</div>

<div class='row'>
	<div class="col-xs-12">
	  <table class='table'>
	    <thead>
	      <tr>
	        <th>商品名</th>
	        <th>単価(税込)</th>
	        <th>数量</th>
	        <th></th>
	        <th>小計</th>
	        <th></th>
	      </tr>
	    </thead>
	    <tbody>
	  	<% total = 0 %>
			<% @cart_items.each do |cart_item| %>
			<tr>
				<td><%= attachment_image_tag cart_item.item, :item_image, :fill, 50, 50, class: "img-rounded profile-img cart_img", fallback: "no_image.png", size: '50x50' %><span><%= cart_item.item.name %></span></td>
				<td><%= (cart_item.item.priceWithTax.to_i).to_s(:delimited) %></td>
	         	<%= form_for([cart_item.item, cart_item]) do |f| %>
     		<td>
     			<%= f.number_field :quantity, min: 1, max: 10,	class: 'form-control input-sm col-xs-10' %>
   			</td>
	 		　	<td>
 					<%= f.submit('変更',class: 'btn btn-primary btn-sm', data: {"turbolinks" => false}) %>
	 			</td>
	 					<td><%= (cart_item.item.priceWithTax.round * cart_item.quantity).to_s(:delimited) %></td>
       	<% end %>
       	<td>
       		<%= link_to '削除する', item_cart_item_path(cart_item.item, cart_item), class:"btn btn-danger btn-sm", method: :delete %>
       	</td>
       	<% (total += cart_item.item.priceWithTax.round * cart_item.quantity).to_s(:delimited)%>
	    </tr>
			<% end %>
	    </tbody>
	  </table>
	</div>
</div>

<div class="row">
	<div class="col-xs-9">
	  <%= link_to '買い物を続ける', items_path, class: "btn btn-primary" %>
	</div>
	<div class="col-xs-3">
 		<table class='table pull-right'>
		    <tr>
		    	<th>合計金額</th>
		    	<td><%= total.to_s(:delimited) %>円</td>
		    </tr>
		</table>
	</div>
</div>
<div class="row">
	<div class="col-xs-3 col-xs-offset-5">
  	<%= link_to '情報入力に進む', new_order_path(@cart_items), class: "btn btn-primary btn-lg" %>
  </div>
</div>