config/routes.rb
Rails.application.routes.draw do

  get '/customers/withdraw', to: 'customers#withdraw'

  namespace :staffs do
     root to: 'home#top'
     #put 'orders/item/:id', to:'orders#item_update', as:'order_item'
     patch 'orders/item/:id', to:'orders#item_update', as:'order_item'
     get 'orders/customers/:id', to:'orders#index', as: 'orders_search'
     resources :orders, only:[ :index, :show, :edit, :update ]


     resources :customers, only:[ :index, :show, :edit, :update, :destroy ]
     resources :items, only:[ :index, :show, :new, :create, :edit, :update ]
     resources :genres, only:[ :index, :new, :create, :edit, :update ]
   end

  devise_for :staffs, controllers: {
        sessions: 'staffs/sessions',
        registrations: 'staffs/registrations'
      }

  root to: 'home#top'
  devise_for :customers, controllers: {
        sessions: 'customers/sessions',
        registrations: 'customers/registrations'
      }


  root to: 'home#top'
  get '/home/about', to: 'home#about'
  resources :customers, only:[ :edit, :show, :update, :destroy ]
  resources :customers, only:[ :edit, :show, :update,:destroy ]
  resources :items, only:[ :index, :show ] do
  resources :cart_items, only: [ :index, :update, :create, :destroy ]
  end
  get 'orders/check', to: 'orders#check'
  get 'orders/thanks', to: 'orders#thanks'

  delete '/cart_items/', to: 'cart_items#clear' #カートアイテム全件削除
  resources :orders, only:[ :index, :new, :create, :show ]
  post 'orders/check', to: 'orders#check'



  resources :sub_addresses, only:[ :index, :show , :new, :create, :edit, :update, :destroy ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end



 #  namespace :admins do
 #    get 'top', to: 'home#top'
	#   resources :orders, only:[ :index, :show, :edit, :update ]
	#   resources :customers, only:[ :index, :show, :edit, :update ]
	#   resources :items, only:[ :index, :show, :new, :create, :edit, :update ]
	#   resources :genres, only:[ :index, :new, :create, :edit, :update ]
	# end

app/models/item.rb
class Item < ApplicationRecord
  attachment :item_image
  has_many :cart_items
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  belongs_to :genre
# 　enum status: { invalid: false, available: true }
  def priceWithTax
    non_taxed_price * 1.1
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
	# def index
	# 	@items = Item.all
	# end

	# def show
	# 	@item = Item.find(params[:id])
	# 	@genre = @item.genre
	# end

	# def new
	# 	@item = Item.new
	# 	@genres = Genre.all #ジャンルのセレクトボックス
	# end

	# def create
	# 	@item = Item.new(item_params)
	# 	@item.save
	# 	redirect_to admins_item_path(@item)
	# end

	# def edit
	# 	@item = Item.find(params[:id])
	# 	@genres = Genre.all #ジャンルのセレクトボックス
	# end

	# def update
	# 	@item = Item.find(params[:id])
	# 	if   @item.update(item_params)
 #     	     flash[:notice] = "You have updated user successfully"
 #    	     redirect_to admins_item_path(@item.id)
 #    	else render 'edit'
 #    	end
	# end

	# private
	# def item_params
	#     params.require(:item).permit(:name, :sale_status, :genre_id, :item_image, :non_taxed_price, :description)
	# end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    if params[:genre_id] != nil
    @items = Item.where(genre_id: params[:genre_id]).page(params[:page])
    @items_count = @items.count
    @genres = Genre.where(genre_status: true)
    @genre = Genre.find(params[:genre_id])
    else
    @items = Item.all.page(params[:page])
    @items_all = Item.all
    @items_count = @items_all.count
    @genres = Genre.where(genre_status: true)
    @genre = Genre.all
    end

  end

  def show
    @item = Item.find(params[:id])
    @genres = Genre.where(genre_status: true)
    @cart_item = CartItem.new
  end

	def new
		@item = Item.new
	end

	private
	def item_params
	  params.require(:item).permit(:name, :item_image, :non_taxed_price, :description)
	  params.require(:cart_item).permit(:quantity)
	end

end

app/controllers/staffs/items_controller.rb
class Staffs::ItemsController < ApplicationController
	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
		@genre = @item.genre
	end

	def new
		@item = Item.new
		@genres = Genre.all #ジャンルのセレクトボックス
	end

	def create
		@item = Item.new(item_params)
		@item.save
		redirect_to staffs_items_path
	end

	def edit
		@item = Item.find(params[:id])
		@genres = Genre.all #ジャンルのセレクトボックス
	end

	def update
		@item = Item.find(params[:id])
		if   @item.update(item_params)
     	     flash[:notice] = "You have updated user successfully"
    	     redirect_to staffs_item_path(@item.id)
    	else render 'edit'
    	end
	end

	private
	def item_params
	    params.require(:item).permit(:name, :sale_status, :genre_id, :item_image, :non_taxed_price, :description)
	end
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/staffs/items_helper.rb
module Staffs::ItemsHelper
end

app/views/items/_genre_list.html.erb
<div class="col-xs-3">
  <article id="genre_list_area">
    <table class="table">
      <thead>
        <tr>
          <th class="table_genre ">
            <span>ジャンル検索</span>
          </th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td style="border-style: none;"><%= link_to "すべて", items_path, class: "genre_text"; %></td>
          </tr>
          <tr>
            <% genres.each do |genre| %>
              <td style="border-style: none;">
                <%= link_to items_path(genre_id: genre.id) do %>
                  <span class="genre_text" ><%= genre.name %></span>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </article>
</div>

app/views/items/devide.html.erb
<div class="row">

  <%= render 'items/genre_list', genres: @genres %>

  <div class="col-xs-9">
    <div class="title"><%= @genre.name %>
      <span class="item_count">全 <%= @items_count %> 件</span>
    </div>

      <div class="item_list_box">
          <% @devide_items.each do |item| %>
          <div class="item">
              <%= attachment_image_tag item, :item_image, :fill, 200, 150, format: 'jpeg', class: "img-rounded pull-left profile-img", fallback: "no_image.jpg", :size =>'200x150' %>
              <div class="item_btn">
              <%= link_to item.name, item_path(item.id), class: "item_link" %>
              </div>
              <div class="price_text">
                <% @item_price = item.non_taxed_price.to_i * 1.1  %>
              ¥<%= @item_price.floor.to_s(:delimited) %>
              </div>
          </div>
          <% end %>
      </div>
  </div>

</div>

app/views/items/index.html.erb
<div class="row">

  <%= render 'items/genre_list', genres: @genres %>


  <div class="col-xs-9">
    <% if params[:genre_id] != nil %>
    <div class="title"><!--商品一覧--><%= @genre.name %>
      <% else %>
      <div class="title">商品一覧
      <% end %>
      <span class="item_count">全 <%= @items_count %> 件</span>

    </div>

      <div class="item_list_box">
          <% @items.each do |item| %>
          <div class="item_content">
              <%= link_to item_path(item.id), class: "item_link" do %>
              <%= attachment_image_tag item, :item_image, :fill, 200, 150, format: 'jpeg', class: "img-rounded pull-left profile-img item_img", fallback: "no_image.jpg", :size =>'200x150' %>
              <% end %>
              <div class="item_btn item_title">
              <%= link_to item.name, item_path(item.id), class: "item_link" %>
              </div>
              <div class="price_text">
                <% @item_price = item.non_taxed_price.to_i * 1.1  %>
              ¥<%= @item_price.floor.to_s(:delimited) %>
              </div>
          </div>
          <% end %>
      </div>
      <%= paginate @items, class: "pagination" %>
  </div>

</div>

app/views/items/show.html.erb
<%= render 'items/genre_list', genres: @genres %>

<div class="col-xs-9">
  <div class="row">
    <div class="col-xs-6">
      <%= attachment_image_tag @item, :item_image, :fill, 300, 200, format: 'jpeg', class: "img-rounded pull-right profile-img", fallback: "no_image.jpg", :size =>'300x200' %>
    </div>
    <div class="col-xs-6">
      <h2 class="item_text"><%= @item.name %></h2>
      <h4 class="item_text"><%= @item.description %></h4>
      <% @item_price = @item.non_taxed_price.to_i * 1.1  %>
      <p class="price">¥<%= @item_price.floor.to_s(:delimited) %><span> (税込) </span></p>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-xs-offset-6 ">
      <%= form_for([@item,@cart_item]) do |f| %>
      <!-- 個数選択 -->
      <div class="row">
        <div class="col-xs-5">
        <span><%= f.label :"個数選択" %>
        <%= f.number_field :quantity, min: 1, max: 10, class:"form-control" %></span>
        </div>
        <div class="col-xs-7">
        <!-- カートに入れる -->
        <%= f.submit "カートに入れる", class: "btn btn-primary btn-lg", data: {"turbolinks" => false}%>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>