config/routes.rb
Rails.application.routes.draw do

  get '/customers/withdraw', to: 'customers#withdraw'

  namespace :staffs do
     root to: 'home#top'
     #put 'orders/item/:id', to:'orders#item_update', as:'order_item'
     patch 'orders/item/:id', to:'orders#item_update', as:'order_item'
     get 'orders/customers/:id', to:'orders#index', as: 'orders_search'
     resources :orders, only:[ :index, :show, :edit, :update ]


     resources :customers, only:[ :index, :show, :edit, :update, :destroy ]
     resources :items, only:[ :index, :show, :new, :create, :edit, :update ]
     resources :genres, only:[ :index, :new, :create, :edit, :update ]
   end

  devise_for :staffs, controllers: {
        sessions: 'staffs/sessions',
        registrations: 'staffs/registrations'
      }

  root to: 'home#top'
  devise_for :customers, controllers: {
        sessions: 'customers/sessions',
        registrations: 'customers/registrations'
      }


  root to: 'home#top'
  get '/home/about', to: 'home#about'
  resources :customers, only:[ :edit, :show, :update, :destroy ]
  resources :customers, only:[ :edit, :show, :update,:destroy ]
  resources :items, only:[ :index, :show ] do
  resources :cart_items, only: [ :index, :update, :create, :destroy ]
  end
  get 'orders/check', to: 'orders#check'
  get 'orders/thanks', to: 'orders#thanks'

  delete '/cart_items/', to: 'cart_items#clear' #カートアイテム全件削除
  resources :orders, only:[ :index, :new, :create, :show ]
  post 'orders/check', to: 'orders#check'



  resources :sub_addresses, only:[ :index, :show , :new, :create, :edit, :update, :destroy ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end



 #  namespace :admins do
 #    get 'top', to: 'home#top'
	#   resources :orders, only:[ :index, :show, :edit, :update ]
	#   resources :customers, only:[ :index, :show, :edit, :update ]
	#   resources :items, only:[ :index, :show, :new, :create, :edit, :update ]
	#   resources :genres, only:[ :index, :new, :create, :edit, :update ]
	# end

app/models/item.rb
class Item < ApplicationRecord
  attachment :item_image
  has_many :cart_items
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  belongs_to :genre
# 　enum status: { invalid: false, available: true }
  def priceWithTax
    non_taxed_price * 1.1
  end
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
	# def index
	# 	@items = Item.all
	# end

	# def show
	# 	@item = Item.find(params[:id])
	# 	@genre = @item.genre
	# end

	# def new
	# 	@item = Item.new
	# 	@genres = Genre.all #ジャンルのセレクトボックス
	# end

	# def create
	# 	@item = Item.new(item_params)
	# 	@item.save
	# 	redirect_to admins_item_path(@item)
	# end

	# def edit
	# 	@item = Item.find(params[:id])
	# 	@genres = Genre.all #ジャンルのセレクトボックス
	# end

	# def update
	# 	@item = Item.find(params[:id])
	# 	if   @item.update(item_params)
 #     	     flash[:notice] = "You have updated user successfully"
 #    	     redirect_to admins_item_path(@item.id)
 #    	else render 'edit'
 #    	end
	# end

	# private
	# def item_params
	#     params.require(:item).permit(:name, :sale_status, :genre_id, :item_image, :non_taxed_price, :description)
	# end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    if params[:genre_id] != nil
    @items = Item.where(genre_id: params[:genre_id]).page(params[:page])
    @items_count = @items.count
    @genres = Genre.where(genre_status: true)
    @genre = Genre.find(params[:genre_id])
    else
    @items = Item.all.page(params[:page])
    @items_all = Item.all
    @items_count = @items_all.count
    @genres = Genre.where(genre_status: true)
    @genre = Genre.all
    end

  end

  def show
    @item = Item.find(params[:id])
    @genres = Genre.where(genre_status: true)
    @cart_item = CartItem.new
  end

	def new
		@item = Item.new
	end

	private
	def item_params
	  params.require(:item).permit(:name, :item_image, :non_taxed_price, :description)
	  params.require(:cart_item).permit(:quantity)
	end

end

app/controllers/staffs/application_controller.rb
class Staffs::ApplicationController < ApplicationController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?


	def after_sign_in_path_for(resource)
    # if resource.is_a?(Staff)
      staffs_root_path
    # else
    	# items_path
  	# end
  end



	private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:surname, :name, :surname_kana, :name_kana, :phone_number, :postal_code, :address, :email, :deleted_at, :encrypted_password])
  end
end

app/controllers/staffs/base_controller.rb
class Staffs::BaseController < ApplicationController
	before action : staff_login_required

  	private def staff_login_required
    	raise Forbidden unless current_member&.staffistrator?
  	end

     def after_sign_up_path_for(resource)
    staffs_home_top_path(resource)
    end
end

app/controllers/staffs/confirmations_controller.rb
# frozen_string_literal: true

class Staff::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/staffs/customers_controller.rb
class Staffs::CustomersController < ApplicationController

def index
    @customers = Customer.with_deleted.page(params[:page])
  end

  def show
  @customer = Customer.with_deleted.find(params[:id])
  end

  def edit
    @customer = Customer.with_deleted.find(params[:id])
  end

  def update
    @customer = Customer.with_deleted.find(params[:id])
    if params[:customer][:deleted_at] == "無効"
    @customer.delete
    else
    @customer.restore
    end

    if @customer.update(customer_params)
      flash[:notice] = "You have updated customer successfully"
      redirect_to staffs_customer_path(@customer.id)
    else
      render 'edit'
    end
    #binding.pry
  end

  #def destroy
    #@customer = Customer.find(params[:id])
    #if @customer.destroy
      #redirect_to staffs_customer_path(@customer.id)
    #end

   private
  def customer_params
    params.require(:customer).permit(:surname, :name, :surname_kana, :name_kana, :phone_number, :postal_code, :address, :email, :customer_status)
  end
end

app/controllers/staffs/genres_controller.rb
class Staffs::GenresController < ApplicationController
  def index
  	@genres = Genre.all
  	@genre = Genre.new
  end

  def new
    @genres = Genre.new
  end

  def create
  	@genre = Genre.new(genre_params)
  	if @genre.save
  		redirect_to staffs_genres_path
    else
      @genres = Genre.all
      render :index
  	end
  end

  def edit
  	@genre = Genre.find(params[:id])
  end


  def update
  	@genre = Genre.find(params[:id])
  	if @genre.update(genre_params)
  		redirect_to staffs_genres_path
  	else
  	　render :edit
  	end
  end


  	private
  	def genre_params
  		params.require(:genre).permit(:name, :genre_status, :created_at)
    end
end

app/controllers/staffs/home_controller.rb
class Staffs::HomeController < ApplicationController
	before_action :authenticate_staff!
  def top
  	@orders_count = Order.where(created_at: Date.current.all_day)
  		.order("created_at")
  		.count
  end
end
 

app/controllers/staffs/items_controller.rb
class Staffs::ItemsController < ApplicationController
	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
		@genre = @item.genre
	end

	def new
		@item = Item.new
		@genres = Genre.all #ジャンルのセレクトボックス
	end

	def create
		@item = Item.new(item_params)
		@item.save
		redirect_to staffs_items_path
	end

	def edit
		@item = Item.find(params[:id])
		@genres = Genre.all #ジャンルのセレクトボックス
	end

	def update
		@item = Item.find(params[:id])
		if   @item.update(item_params)
     	     flash[:notice] = "You have updated user successfully"
    	     redirect_to staffs_item_path(@item.id)
    	else render 'edit'
    	end
	end

	private
	def item_params
	    params.require(:item).permit(:name, :sale_status, :genre_id, :item_image, :non_taxed_price, :description)
	end
end

app/controllers/staffs/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Staff::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/staffs/orders_controller.rb
class Staffs::OrdersController < ApplicationController

	def index

	#	if params[:place] && params[:place] == 'top'
  #   	@orders = Order.where(created_at: Date.current.all_day)
  #      .order("created_at")
  #  	@orders_count = @orders.count

	#	elsif params[:customer_id] != nil
	#		@orders = Order.where(customer_id: params[:customer_id]).page(params[:page]).reverse_order
  #  else
   # 	@orders = Order.all
   #	end

	  if params[:place] && params[:place] == 'top'
         	@orders = Order.where(created_at: Date.current.all_day)
            .order("created_at")
        	@orders_count = @orders.count
    elsif params[:customer_id] != nil
			@orders = Order.where(customer_id: params[:customer_id]).page(params[:page]).reverse_order
		else
			#binding.pry
			@orders = Order.all
			# @all_orders = @customer
		end

	end

	def show
    	@order = Order.find(params[:id])
		# @orders = @order.order_items
		# @items = @orders.items
		# @subtotal = @items.subtotal #小計
	end

	def edit
		@genre = Genre.all
		@order = Order.find(params[:id])
		@status = OrderItems.find(params[:id])
	end

	def update
		@order = Order.find(params[:id])
		@order_items = @order.order_items
		@order.update(order_params)

		if @order.order_status == 'varification'
		   	@order.order_items.update(create_status: 'waiting')
		   	 redirect_to staffs_order_path(@order)
		else
			redirect_to staffs_order_path(@order)
		end
	end
	def item_update
		order_item = OrderItem.find(params[:id])
		@order = order_item.order
		@order_items=@order.order_items
		order_item.update(order_item_params)
		if order_item.create_status=='making' && @order.order_status!='production'
		   @order.update(order_status: 'production')
		elsif order_item.create_status == 'completed'
			answer = true
			@order_items.each do |ord_items|
				if ord_items.create_status!='completed'
					answer=false
				end
			end
			if answer
			  	@order.update(order_status: 'preparing')
		  	end
		end
		redirect_to staffs_order_path(order_item.order.id)
	end

	private
	def order_params
	    params.require(:order).permit(:shipping_address, :order_status, :method_of_payment)
	    # params.require(:order_item).premit(:order_quantity, :tax_inckluded_price, :create_status)
	end

	def order_item_params
		params.require(:order_item).permit(:create_status)
	end

	def place_params
		params.require(:place).permit("top")
	end
end

app/controllers/staffs/passwords_controller.rb
# frozen_string_literal: true

class Staff::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/staffs/registrations_controller.rb
# frozen_string_literal: true

class Staff::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/staffs/sessions_controller.rb
# frozen_string_literal: true

class Staffs::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
layout false

end

app/controllers/staffs/unlocks_controller.rb
# frozen_string_literal: true

class Staff::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/staffs/application_helper.rb
module Staffs::ApplicationHelper
end

app/views/staffs/items/edit.html.erb
<div class ='body'>
  <div class ='container'>
    <h3>商品編集画面</h3>
     <div class="row">
      <div class="col-xs-4">
        <%= form_for @item, url: staffs_item_path(@item) do |f| %>
        <%= attachment_image_tag @item, :item_image, :fill, 400, 400, fallback: "no_image.png", size: '200x200'  %>
      </div>
        <div class="col-xs-5">
          <div class = "form-group">
            <%= f.attachment_field :item_image %>
          </div>
          <div class = "form-group">
            <label for="user_name">商品名</label>
            <%= f.text_field :name, class:"form-control" %>
          </div>

          <div class = "form-group">
            <label for="user_name">商品説明</label>
            <%= f.text_area :description, class:"form-control" %>
          </div>
          <div class = "form-group">
            <label for="user_name">ジャンル</label>
            <%= f.collection_select(:genre_id, @genres, :id, :name) %>
          </div>
          <div class = "form-group">
            <label for="user_name">税抜価格</label>
            <%= f.text_field :non_taxed_price %>円
          </div>
          <div class = "form-group">
            <label for="user_name">販売ステータス</label>
            <%= f.select :sale_status,[["販売中",1],["売り切れ",0]]%>
          </div>
          <div class = "form-group">
              <%= f.submit "編集", class: "btn btn-primary" %>
          </div>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/staffs/items/index.html.erb
<div class='row'>
  <h2>商品一覧画面</h2>
    <table class="table table-hover table-inverse">
      <%= link_to "商品追加", new_staffs_item_path, class: "btn btn-default pull-left" %>
        <thead>
          <tr>
            <th>注文ID</th>
            <th>商品名</th>
            <th>税抜き価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
           <td><%= item.id %></td>
           <td><%= link_to item.name, staffs_item_path(item.id) %></td>
           <td><%= item.non_taxed_price.to_s(:delimited) %></td>
           <td><%= item.genre.name %></td>
           <td>
              <% if item.sale_status == true %>
              販売中
              <% else %>
              売り切れ
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </div>
  </table>
</div>

app/views/staffs/items/new.html.erb
<div class="body">
    <div class="container">
    <h2>商品新規登録画面</h2>
      <%= form_for @item, url: staffs_items_path do |f| %>
        <div class = "form-group">
            <div class="field">
             <%= attachment_image_tag @item, :item_image, :fill, 200, 200, fallback: "no_image.png", size: '200x200'  %>
              <%= f.attachment_field :item_image %>
            </div>

            <div class="field">
                <label for="user_name">商品名</label>
                <%= f.text_field :name %>
            </div>

            <div class="field">
                <label for="user_name">商品説明</label>
                <%= f.text_area :description, size: "50x10" %>
            </div>

            <div class="field">
                <label for="user_name">ジャンル</label>
                <%= f.collection_select(:genre_id, @genres, :id, :name) %>
            </div>

            <div class="field">
                <label for="user_name">税抜価格</label>
                <%= f.text_field :non_taxed_price %>円
            </div>

            <div class="field">
                <label for="user_name">販売ステータス</label>
                <%= f.select :sale_status,[["売り切れ",0],["販売中",1]]%>
            </div>

            <div class="field">
              <%= f.submit "新規登録" %>
            </div>
        </div>
      <% end %>
    </div>
</div>

app/views/staffs/items/show.html.erb
<h2>商品詳細画面</h2>
  <div class="row">
    <div class="col-xs-4">
        <%= attachment_image_tag @item, :item_image, :fill, 600, 400, fallback: "no_image.png", size: '300x200'  %>
    </div>
    <div class="col-xs-8">
      <table class='item_detail_table'>
            <tr>
              <th>商品名</th>
              <th><%= @item.name %></th>
            </tr>
            <tr>
              <th>商品説明</th>
              <th><%= @item.description %></th>
            </tr>
            <tr>
              <th>ジャンル</th>
              <th><%= @item.genre.name %></th>
            </tr>
            <tr>
              <th>税込価格（税抜価格）</th>
              <th><%= (@item.priceWithTax.to_i).to_s(:delimited) %>(<%= (@item.non_taxed_price.to_i).to_s(:delimited) %>)円</th>
            </tr>
            <tr>
            <th>販売ステータス</th>
            <th>
            　<% if @item.sale_status == true %>
              販売中
              <% else %>
              売り切れ
              <% end %>
            </th>
            </tr>
      </table>
          <%= link_to '編集する', edit_staffs_item_path(@item), class: "btn btn-primary btn-lg pull-right", data: {"turbolinks" => false} %>
    </div>
  </div>